version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: edugame4all-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-edugame4all}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - edugame4all-network

  # Backend API (Node.js/Express)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: edugame4all-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000
      DATABASE_URL: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password}@mongodb:27017/${MONGO_DB:-edugame4all}?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-in-production}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET:-your-refresh-token-secret-change-in-production}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:5173,http://localhost:3000}
      AI_SERVICE_URL: http://ai-services:8001
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    depends_on:
      - mongodb
      - ai-services
    networks:
      - edugame4all-network
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend (React/Vite)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: edugame4all-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
      VITE_AI_SERVICE_URL: http://localhost:8001
    depends_on:
      - backend
    networks:
      - edugame4all-network
    volumes:
      - ./client:/app
      - /app/node_modules

  # AI Services (Python/FastAPI)
  ai-services:
    build:
      context: ./ai-services
      dockerfile: Dockerfile
    container_name: edugame4all-ai-services
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      AI_SERVICE_PORT: 8001
      HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      LLM_MODEL: ${LLM_MODEL:-meta-llama/Llama-3.1-8B-Instruct}
      WHISPER_MODEL: ${WHISPER_MODEL:-large-v3}
      USE_GPU: ${USE_GPU:-false}
      CACHE_DIR: /app/models
    volumes:
      - ai_models:/app/models
    networks:
      - edugame4all-network
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  ai_models:
    driver: local

networks:
  edugame4all-network:
    driver: bridge
